# -*- coding: utf-8 -*-
"""UGC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRfuGaZJctU_-m-LbHxLuafUHjPpi5oM

# Fine-tune Llama 3.1 8B with Unsloth
> 🗣️ [Large Language Model Course](https://github.com/mlabonne/llm-course)
"""

!pip install -qqq "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git" --progress-bar off
from torch import __version__; from packaging.version import Version as V
xformers = "xformers==0.0.27" if V(__version__) < V("2.4.0") else "xformers"
!pip install -qqq --no-deps {xformers} trl peft accelerate bitsandbytes triton --progress-bar off

import torch
from trl import SFTTrainer
from datasets import load_dataset
from transformers import TrainingArguments, TextStreamer
from unsloth.chat_templates import get_chat_template
from unsloth import FastLanguageModel, is_bfloat16_supported

"""# Requirements-lock"""

# Run this cell in your Colab notebook
import subprocess

# Get ALL installed packages with exact versions
result = subprocess.run(['pip', 'freeze'], capture_output=True, text=True)
with open('colab_requirements.txt', 'w') as f:
    f.write(result.stdout)

# Also get CUDA/GPU info
cuda_info = subprocess.run(['nvcc', '--version'], capture_output=True, text=True)
nvidia_info = subprocess.run(['nvidia-smi'], capture_output=True, text=True)

print("=== CUDA VERSION ===")
print(cuda_info.stdout)
print("\n=== GPU INFO ===")
print(nvidia_info.stdout)

print("\n=== requirements.txt saved! Download it from the Files panel ===")

!python --version

import warnings
# Only ignore warnings about deprecated features
warnings.filterwarnings('ignore', category=DeprecationWarning)

"""## 1. Load model for PEFT"""

# Load model
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Meta-Llama-3.1-8B-bnb-4bit",
    max_seq_length=max_seq_length,
    load_in_4bit=True,
    dtype=None,
)

# Prepare model for PEFT
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=16,
    lora_dropout=0,
    target_modules=["q_proj", "k_proj", "v_proj", "up_proj", "down_proj", "o_proj", "gate_proj"],
    use_rslora=True,
    use_gradient_checkpointing="unsloth"
)
print(model.print_trainable_parameters())

"""## 2. Prepare data and tokenizer"""

tokenizer = get_chat_template(
    tokenizer,
    chat_template="llama-3"
)

dataset = load_dataset("json", data_files="train.jsonl", split="train")

# Format using LLaMA 3 chat template
def format_example(example):
    return {"text": tokenizer.apply_chat_template(
        example["conversations"],
        tokenize=False,
        add_generation_prompt=False
    )}

dataset = dataset.map(format_example)

EOS_TOKEN = tokenizer.eos_token

def add_eos(example):
    example["text"] = example["text"] + EOS_TOKEN
    return example

train_dataset = dataset.map(add_eos)

# Evaluation dataset

tokenizer = get_chat_template(
    tokenizer,
    chat_template="llama-3"
)

dataset = load_dataset("json", data_files="val.jsonl", split="train")

# Format using LLaMA 3 chat template
def format_example(example):
    return {"text": tokenizer.apply_chat_template(
        example["conversations"],
        tokenize=False,
        add_generation_prompt=False
    )}

dataset = dataset.map(format_example)

EOS_TOKEN = tokenizer.eos_token

def add_eos(example):
    example["text"] = example["text"] + EOS_TOKEN
    return example

eval_dataset = dataset.map(add_eos)

eval_dataset[0]

"""## 3. Training(finetuning)"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir /content/drive/MyDrive/llm_training_output

# from trl import SFTTrainer, SFTConfig
# import os

# # Create a dedicated folder in your Google Drive
# output_directory = "/content/drive/MyDrive/llm_training_output"
# os.makedirs(output_directory, exist_ok=True)

# trainer = SFTTrainer(
#     model=model,
#     processing_class=tokenizer,
#     train_dataset=dataset,
#     args=SFTConfig(
#         dataset_text_field="text",
#         max_length=max_seq_length,
#         packing=True,
#         dataset_num_proc=2,

#         learning_rate=3e-4,
#         lr_scheduler_type="linear",
#         per_device_train_batch_size=4,
#         gradient_accumulation_steps=4,
#         num_train_epochs=3,

#         fp16=not is_bfloat16_supported(),
#         bf16=is_bfloat16_supported(),

#         logging_steps=1,
#         optim="adamw_8bit",
#         weight_decay=0.01,
#         warmup_steps=10,
#         output_dir="output",
#         seed=0,
#     ),
# )

# trainer.train()

# # Explicitly save the final fine-tuned model at the end
# trainer.save_model(os.path.join(output_directory, "final_model"))



from trl import SFTTrainer, SFTConfig
from transformers import EarlyStoppingCallback
import os

# =========================================================
# OUTPUT DIRECTORY
# =========================================================

output_directory = "/content/drive/MyDrive/llm_training_output"
os.makedirs(output_directory, exist_ok=True)

# =========================================================
# TRAINER
# =========================================================

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,

    train_dataset=train_dataset,
    eval_dataset=eval_dataset,   # IMPORTANT

    args=SFTConfig(
        # ======================
        # DATASET
        # ======================
        dataset_text_field="text",
        max_length=max_seq_length,
        packing=True,
        dataset_num_proc=2,

        # ======================
        # TRAINING
        # ======================
        learning_rate=3e-4,
        lr_scheduler_type="cosine",

        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,

        num_train_epochs=3,

        # ======================
        # PRECISION
        # ======================
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),

        # ======================
        # OPTIMIZATION
        # ======================
        optim="adamw_8bit",
        weight_decay=0.01,
        warmup_ratio=0.03,

        # ======================
        # LOGGING
        # ======================
        logging_steps=1,

        report_to="tensorboard",   # REAL TIME VISUALIZATION

        # ======================
        # EVALUATION
        # ======================
        eval_strategy="steps",
        eval_steps=1,

        # ======================
        # CHECKPOINTING
        # ======================
        save_strategy="steps",
        save_steps=1,

        save_total_limit=3,   # keep only latest 3 checkpoints

        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,

        # ======================
        # OUTPUT
        # ======================
        output_dir=output_directory,

        # ======================
        # MEMORY OPTIMIZATION
        # ======================
        gradient_checkpointing=True,

        # ======================
        # OTHER
        # ======================
        seed=0,
    ),

    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=3
        )
    ]
)

# =========================================================
# TRAIN
# =========================================================

trainer.train()

# =========================================================
# SAVE BEST MODEL
# =========================================================

best_model_path = os.path.join(output_directory, "best_model")

trainer.save_model(best_model_path)
tokenizer.save_pretrained(best_model_path)

"""## 4. Inference"""

from unsloth import FastLanguageModel

# 1. Load the saved fine-tuned model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/llm_training_output/final_model",
    max_seq_length=2048,
    load_in_4bit=True,
)

# 2. Switch to inference mode (important!)
FastLanguageModel.for_inference(model)

# 3. Prepare your input message
messages = [
    {
        "role": "system",
        "content": "You are a real estate lead qualification assistant for Anywhere Real Estate (operating brands including Coldwell Banker, Century 21, ERA, Sotheby's International Realty, Better Homes and Gardens Real Estate, and Corcoran). Given a lead conversation, output a JSON with: intent (buy/rent/invest/browse), urgency (hot/warm/cold), budget_range, timeline_months, preferred_locality, property_type, brand_fit (which Anywhere brand best matches the lead), next_action (agent_call/schedule_showing/follow_up_email/nurture_sequence/drop), score (0–100), and reasoning."
    },
    {
        "role": "user",
        "content": """Lead conversation:
User: Hi, I'm looking to buy a home in Austin, TX. Budget is around $600k.
Agent: Great! Are you pre-approved and what's your timeline?
User: Yes, pre-approved. We want to close within 3 months."""
    }
]
tokenizer = get_chat_template(
    tokenizer,
    chat_template="llama-3",
    # mapping={"role" : "from", "content" : "value", "user" : "human", "assistant" : "gpt"}
)

# 4. Apply chat template
input_ids = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,   # ← adds the assistant header to trigger generation
    return_tensors="pt",
).to("cuda")

# 5. Generate output
outputs = model.generate(
    input_ids=input_ids,
    # max_new_tokens=512,
    temperature=0.1,        # low temp for consistent JSON output
    do_sample=True,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.eos_token_id,
)

# 6. Decode only the newly generated tokens
generated = outputs[0][input_ids.shape[-1]:]
response = tokenizer.decode(generated, skip_special_tokens=True)
print(response)

"""# Model Evaluation"""

from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
import torch
import json
from torch.utils.data import DataLoader

# ─────────────────────────────────────────────
# 1. Load model
# ─────────────────────────────────────────────
# model, tokenizer = FastLanguageModel.from_pretrained(
#     model_name="/content/drive/MyDrive/llm_training_output/final_model",
#     max_seq_length=2048,
#     load_in_4bit=True,
# )

# FastLanguageModel.for_inference(model)

# tokenizer = get_chat_template(
#     tokenizer,
#     chat_template="llama-3",
# )

# ─────────────────────────────────────────────
# 2. Load .jsonl evaluation file
#    Each line: {"conversations": [{role, content}, ...]}
# ─────────────────────────────────────────────
def load_jsonl(file_path):
    samples = []
    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                samples.append(json.loads(line))
    return samples

val_samples = load_jsonl("/content/val.jsonl")
print(f"✅ Loaded {len(val_samples)} evaluation samples")

# ─────────────────────────────────────────────
# 3. Tokenize with labels
#    - "conversations" key → rename to "messages"
#    - Mask prompt tokens with -100
#    - Loss computed only on assistant response
# ─────────────────────────────────────────────
def tokenize_with_labels(sample, tokenizer, max_seq_length=2048):
    # Your data uses "conversations" key
    messages = sample["conversations"]

    # Full conversation (prompt + assistant response)
    full_ids = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=False,
        return_tensors="pt",
    ).squeeze(0)

    # Prompt only (system + user, without assistant turn)
    prompt_ids = tokenizer.apply_chat_template(
        messages[:-1],              # everything except last assistant message
        tokenize=True,
        add_generation_prompt=True, # adds assistant header token
        return_tensors="pt",
    ).squeeze(0)

    prompt_len = prompt_ids.shape[0]

    # Mask prompt tokens → loss only on assistant response
    labels = full_ids.clone()
    labels[:prompt_len] = -100

    # Truncate to max_seq_length
    full_ids = full_ids[:max_seq_length]
    labels   = labels[:max_seq_length]

    return {"input_ids": full_ids, "labels": labels}


tokenized = [tokenize_with_labels(s, tokenizer) for s in val_samples]
print(f"✅ Tokenized {len(tokenized)} samples")

# ─────────────────────────────────────────────
# 4. Collate batch (pad to same length)
# ─────────────────────────────────────────────
def collate_fn(batch):
    max_len = max(b["input_ids"].shape[0] for b in batch)

    input_ids_padded = []
    labels_padded    = []
    attention_masks  = []

    for b in batch:
        pad_len = max_len - b["input_ids"].shape[0]

        input_ids_padded.append(
            torch.cat([b["input_ids"],
                       torch.full((pad_len,), tokenizer.pad_token_id)])
        )
        labels_padded.append(
            torch.cat([b["labels"],
                       torch.full((pad_len,), -100)])   # ignore padding in loss
        )
        attention_masks.append(
            torch.cat([torch.ones(b["input_ids"].shape[0]),
                       torch.zeros(pad_len)])
        )

    return {
        "input_ids":      torch.stack(input_ids_padded).long(),
        "labels":         torch.stack(labels_padded).long(),
        "attention_mask": torch.stack(attention_masks).long(),
    }


val_loader = DataLoader(tokenized, batch_size=2, collate_fn=collate_fn)

# ─────────────────────────────────────────────
# 5. Compute evaluation loss
# ─────────────────────────────────────────────
model.eval()
total_loss   = 0.0
total_tokens = 0

print("\n⏳ Running evaluation...")
print("\n Evaluation loss in batches as given below: ")

with torch.no_grad():
    for i, batch in enumerate(val_loader):
        input_ids      = batch["input_ids"].to("cuda")
        labels         = batch["labels"].to("cuda")
        attention_mask = batch["attention_mask"].to("cuda")

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )

        non_masked_tokens = (labels != -100).sum().item()
        total_loss       += outputs.loss.item() * non_masked_tokens
        total_tokens     += non_masked_tokens

        print(f"  Batch {i+1}/{len(val_loader)} | "
              f"Batch Loss: {outputs.loss.item():.4f} | "
              f"Tokens: {non_masked_tokens}")

# ─────────────────────────────────────────────
# 6. Final results
# ─────────────────────────────────────────────
avg_loss   = total_loss / total_tokens
perplexity = torch.exp(torch.tensor(avg_loss)).item()

print(f"\n{'━'*40}")
print(f"  ✅ Eval Loss   : {avg_loss:.4f}")
print(f"  ✅ Perplexity  : {perplexity:.4f}")
print(f"  📊 Total Tokens evaluated : {total_tokens}")
print(f"{'━'*40}")

# ─────────────────────────────────────────────
# 7. Interpret results
# ─────────────────────────────────────────────
if avg_loss < 0.5:
    print("🟢 Excellent — model reliably generates correct JSON output")
elif avg_loss < 1.5:
    print("🟡 Good — minor formatting inconsistencies possible")
else:
    print("🔴 High loss — consider more fine-tuning data")

"""## 5. Save trained model"""

model.save_pretrained_merged("model", tokenizer, save_method="merged_16bit")
model.push_to_hub_merged("mlabonne/FineLlama-3.1-8B", tokenizer, save_method="merged_16bit")

model.save_pretrained_gguf("model", tokenizer, "q8_0")
quant_methods = ["q2_k", "q3_k_m", "q4_k_m", "q5_k_m", "q6_k", "q8_0"]
for quant in quant_methods:
    model.push_to_hub_gguf("mlabonne/FineLlama-3.1-8B-GGUF", tokenizer, quant)